---
# Home server/NAS
- hosts: all
  become: yes

  pre_tasks:
    - name: Remove snap functionality
      import_tasks: tasks/yeet_snaps.yml
      tags: nosnaps

  roles:
    ######--- SYSTEM ---######
    - role: system/mergerfs

    - role: system/filesystems

    - role: system/mounts
    ######--- /SYSTEM ---######

    - role: network/tailscale

    - role: docker

    ######--- CONTAINERS ---######
    - role: network/NPM
      tags:
        - containers

    - role: applications/nextcloud
      tags:
        - nextcloud
        - containers

    - role: applications/jellyfin
      tags:
        - jellyfin
        - containers
    ######--- /CONTAINERS ---######
