---
# probably not necessary on 21.10
- name: Ensure the core* snaps aren't mounted
  mount:
    name: "/snap/core*"
    state: unmounted

- name: Ensure the pre-installed snaps are removed
  snap:
    name: "{{ item }}"
    state: absent
  with_items:
    - lxd
    - core20
    - snapd
  ignore_errors: yes

- name: Ensure the snap package is not present
  apt:
    package: snapd
    state: absent
    purge: yes

- name: Ensure the snap folders are removed
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /home/{{ username }}/snap
    - /var/snap
    - /var/lib/snap

# TODO: apt module has no hold option,
# and this one doesn't work when a package isn't installed.
# - name: Make sure snap will not be reinstalled somehow
#   dpkg_selections:
#     name: snapd
#     selection: hold
