version: '3'

volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  nextcloud-net:
  npm-net:

services:

  nextcloud-app:
    container_name: nextcloud-app
    image: nextcloud
    restart: always
    volumes:
      - /home/vagrant/nextcloud-app:/var/www/html
    environment:
      - MYSQL_PASSWORD=<STRONG_PASSWORD_HERE>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
    networks:
      - nextcloud-net
      - npm-net

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - /home/vagrant/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<STRONG_PASSWORD_HERE>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=<STRONG_PASSWORD_HERE>
    networks:
      - nextcloud-net

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: always
    networks:
      - nextcloud-net
