---
- name: Make sure that QuickSync packages are installed
  become: yes
  apt:
    name:
      - vainfo
      - intel-media-va-driver-non-free
    state: latest
    update_cache: yes

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/jellyfin"
    pull: yes
    networks:
      - name: npm-net
    privileged: yes
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    state: 'started'
    env:
      "DOCKER_MODS": "linuxserver/mods:jellyfin-opencl-intel"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/TV:/data/tvshows"
      - "{{ mergerfs_root }}/Media/Movies:/data/movies"
      # TODO: convert to slow pool when ready
      - "{{ mergerfs_root }}/Media/Transcodes:/config/data/transcodes"
      - "{{ mergerfs_root }}/Media/Metadata:/config/data/metadata"
      - "{{ mergerfs_root }}/Media/Cache:/config/cache"
      # - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
