---
- name: Create an ext4 filesystem on /dev/sdc and check disk blocks
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdc
    opts: -L data1
    # opts: -cc

- name: Create an ext4 filesystem on /dev/sdd and check disk blocks
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sdd
    opts: -L data2
