---
- name: Ensure an ext4 filesystem is present on each disk
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item.dev }}"
    opts: "-L {{ item.label }}"
  with_items: "{{ disks }}"
  when: disks[0] is defined
    # opts: -cc
