---
- name: Create an ext4 filesystem on each disk and check disk blocks
  community.general.filesystem:
    fstype: ext4
    dev: "{{ item.dev }}"
    opts: "-L {{ item.label }}"
  with_items: "{{ disks }}"
  when: disks[0] is defined
    # opts: -cc
