---
- name: Make sure the Deluge container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "binhex/arch-delugevpn:latest"
    pull: yes
    networks:
      - name: npm-net
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities:
      - net_admin
    state: 'started'
    env:
      "VPN_ENABLED": "yes"
      "VPN_PROV": custom
      "VPN_CLIENT": "wireguard"
      "ENABLE_PRIVOXY": "yes"
      # "NAME_SERVERS": "{{ ','.join(dns_nameservers) }}"
      "LAN_NETWORK": "192.168.178.0/24"
      "DELUGE_DAEMON_LOG_LEVEL": "info"
      "DELUGE_WEB_LOG_LEVEL": "info"
      "DEBUG": "false"
      "UMASK": "000"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    ports:
      - "8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58946"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ mergerfs_root }}/Downloads:/home/nobody/Downloads"
      # - "/etc/localtime:/etc/localtime:ro"
    restart_policy: unless-stopped
