---
- name: Ensure data drives are mounted
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    state: mounted
    passno: "2"
  with_items: "{{ disks }}"
  when: disks[0] is defined

- name: Ensure mergerfs array is mounted
  mount:
    name: "{{ mergerfs_root }}"
    src: /mnt/data*
    opts: direct_io,defaults,allow_other,moveonenospc=1,minfreespace=5G,fsname=mergerfs
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined
