---
- name: Mount the data drives
  mount:
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: ext4
    state: mounted
    passno: "2"
  with_items: "{{ disks }}"
  when: disks[0] is defined

- name: Mount the mergerfs array
  mount:
    name: "{{ mergerfs_root }}_slow"
    src: /mnt/data*
    opts: direct_io,defaults,allow_other,moveonenospc=1,minfreespace=5G,fsname=mergerfs_slow
    fstype: fuse.mergerfs
    state: mounted
  when: disks[0] is defined
