---
- name: Ensure Tailscale's package signing key is imported
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/impish.gpg
    state: present

- name: Add Tailscale's repository
  shell: curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/impish.list | sudo tee /etc/apt/sources.list.d/tailscale.list

- name: Make sure Tailscale is installed
  apt:
    update_cache: yes
    name: tailscale
    state: latest

# NOTE: Tailscale setup is not fully automated because authentication has to be done via the browser
# - name: Make sure tailscale is up
#   command: sudo tailscale up
